# Generated by Django 6.0.2 on 2026-04-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationoption',
            name='option_type',
            field=models.CharField(choices=[('font', 'Font Style Selection'), ('color', 'Color Selection')], default='font', max_length=10),
        ),
        migrations.AlterField(
            model_name='customizationoption',
            name='option_name',
            field=models.CharField(max_length=200),
        ),
    ]
