# Generated by Django 6.0.2 on 2026-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customizationoption_option_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizationvalue',
            name='value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AddField(
            model_name='customizationvalue',
            name='color_value',
            field=models.CharField(blank=True, choices=[('#3D3D3D', 'Charcoal Black'), ('#D4AF37', 'Luxury Gold'), ('#C0C0C0', 'Silver Sparkle'), ('#8A9A5B', 'Sage Green'), ('#B5838D', 'Rose Pink'), ('#E2725B', 'Terracotta')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customizationvalue',
            name='font_value',
            field=models.CharField(blank=True, choices=[("'Playfair Display', serif", 'Classic (Playfair)'), ("'Dancing Script', cursive", 'Elegant (Dancing Script)'), ("'Cinzel', serif", 'Royal (Cinzel)'), ("'Sacramento', cursive", 'Boho (Sacramento)'), ("'Bebas Neue', sans-serif", 'Modern (Bebas)'), ("'Lora', serif", 'Poetry (Lora)')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customizationoption',
            name='option_type',
            field=models.CharField(choices=[('font', 'Font Style Selection'), ('color', 'Color Selection')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
