# Generated by Django 6.0.2 on 2026-04-01 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_category_options_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customizationvalue',
            name='option',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='customizable',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(default=False, help_text='Enable customization section?'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_color_picker',
            field=models.BooleanField(default=False, help_text='Show standard color options?'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_font_picker',
            field=models.BooleanField(default=False, help_text='Show standard font options?'),
        ),
        migrations.CreateModel(
            name='ExtraCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Select Size', max_length=100)),
                ('values', models.CharField(help_text='Enter choices separated by commas: Small, Medium, Large', max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_options', to='store.product')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomizationOption',
        ),
        migrations.DeleteModel(
            name='CustomizationValue',
        ),
    ]
