# Generated by Django 6.0.2 on 2026-04-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
